In [1]:
import numpy as np
import pandas as pd

In [2]:
# **Data Manipulation**


> **Data Preparation**

>> Loading
>> Assembling
>> Merging
>> Concatenation
>> Combining
>> Reshaping (Pivoting)
>> Removing

> Data Transformation

> Data Aggregation







SyntaxError: invalid syntax (Temp/ipykernel_10952/4227194501.py, line 4)

**Merging**

In [3]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [4]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [5]:
pd.merge(frame1,frame2)


id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

**Two dataframes having more than one columns with the same name.**

In [6]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'color': ['white','red','red','black','green'],
'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [7]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [8]:
 pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

**To have two dataframes in which the key columns do not have the same name. **

In [9]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [10]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [12]:
frame2.columns = ['brand','sid']
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

By default the merge() function performs an inner join; the keys in the result are the 
result of an intersection.

Other possible options are the left join, the right join, and the outer join. The outer 
join produces the union of all keys, combining the effect of a left join with a right join. 

To 
select the type of join you have to use the how option.

In [16]:
frame2.columns = ['brand','id']

In [17]:
pd.merge(frame1,frame2,on='id')

Empty DataFrame
Columns: [id, color, brand_x, brand_y]
Index: []

In [18]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [19]:
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN

In [20]:
pd.merge(frame1,frame2,on='id',how='right')

id color brand_x brand_y
0  OMG   NaN     NaN  pencil
1  POD   NaN     NaN  pencil
2  ABC   NaN     NaN    ball
3  POD   NaN     NaN     pen

In [21]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color   brand
0     ball  white     OMG
1   pencil    red     ABC
2      pen    red     ABC
3      mug  black     POD
4  ashtray  green     POD
5      OMG    NaN  pencil
6      POD    NaN  pencil
7      ABC    NaN    ball
8      POD    NaN     pen

**Merging on an Index**

In some cases, instead of considering the columns of a dataframe as keys, indexes could 
be used as keys for merging. 

Then in order to decide which indexes to consider, you 
set the left_index or right_index options to True to activate them, with the ability to 
activate them both.

In [26]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x brand_y id_y
0    ball  white     OMG  pencil  OMG
1  pencil    red     ABC  pencil  POD
2     pen    red     ABC    ball  ABC
3     mug  black     POD     pen  POD

**join()** function, which is much more convenient 
when you want to do the merging by indexes. 

It can also be used to combine many 
dataframe objects having the same or the same indexes but with no columns overlapping.

In [44]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [32]:
frame2

brand   id
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [33]:
 frame1.join(frame2)#error code because some columns in frame1 have the same name as 
#frame2

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [34]:
# Join function merge by index
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

**Concatenating** --  Another type of data combination

NumPy provides a 
concatenate() function to do this kind of operation with arrays.

In [35]:
array1 = np.arange(9).reshape((3,3))
array1 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
array2 = np.arange(9).reshape((3,3))+6
array2 

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
## Column axis
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [38]:
# Row-axis
np.concatenate([array1,array2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
 ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
 ser1

1    0.733198
2    0.263254
3    0.379160
4    0.542869
dtype: float64

In [40]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.229275
6    0.312261
7    0.961590
8    0.550215
dtype: float64

In [41]:
# Row-axis
pd.concat([ser1,ser2])

1    0.733198
2    0.263254
3    0.379160
4    0.542869
5    0.229275
6    0.312261
7    0.961590
8    0.550215
dtype: float64

In [42]:
# Column-axis
pd.concat([ser1,ser2],axis=1)

0         1
1  0.733198       NaN
2  0.263254       NaN
3  0.379160       NaN
4  0.542869       NaN
5       NaN  0.229275
6       NaN  0.312261
7       NaN  0.961590
8       NaN  0.550215

In [43]:
# to create a hierarchical index on the axis of concatenation. 
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.733198
   2    0.263254
   3    0.379160
   4    0.542869
2  5    0.229275
   6    0.312261
   7    0.961590
   8    0.550215
dtype: float64

In [45]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.733198       NaN
2  0.263254       NaN
3  0.379160       NaN
4  0.542869       NaN
5       NaN  0.229275
6       NaN  0.312261
7       NaN  0.961590
8       NaN  0.550215

**Dataframe Concatenation**

In [46]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3], 
columns=['A','B','C'])
frame1

A         B         C
1  0.820320  0.340634  0.559161
2  0.437286  0.071503  0.592347
3  0.804862  0.637393  0.077790

In [47]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], 
columns=['A','B','C'])
frame2

A         B         C
4  0.496734  0.436141  0.398751
5  0.488490  0.731292  0.251043
6  0.463451  0.517931  0.759255

In [48]:
pd.concat([frame1, frame2])

A         B         C
1  0.820320  0.340634  0.559161
2  0.437286  0.071503  0.592347
3  0.804862  0.637393  0.077790
4  0.496734  0.436141  0.398751
5  0.488490  0.731292  0.251043
6  0.463451  0.517931  0.759255

In [49]:
 pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.820320  0.340634  0.559161       NaN       NaN       NaN
2  0.437286  0.071503  0.592347       NaN       NaN       NaN
3  0.804862  0.637393  0.077790       NaN       NaN       NaN
4       NaN       NaN       NaN  0.496734  0.436141  0.398751
5       NaN       NaN       NaN  0.488490  0.731292  0.251043
6       NaN       NaN       NaN  0.463451  0.517931  0.759255

# **Combining**

There is another situation in which there is combination of data that cannot be obtained 
either with merging or with concatenation. 

Take the case in which you want the two 
datasets to have indexes that overlap in their entirety or at least partially.

In [50]:
# Combine Series
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.159451
2    0.699850
3    0.754945
4    0.991947
5    0.417926
dtype: float64

In [51]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.678949
4    0.741397
5    0.446231
6    0.964525
dtype: float64

In [52]:
ser1.combine_first(ser2)

1    0.159451
2    0.699850
3    0.754945
4    0.991947
5    0.417926
6    0.964525
dtype: float64

In [53]:
ser2.combine_first(ser1)

1    0.159451
2    0.678949
3    0.754945
4    0.741397
5    0.446231
6    0.964525
dtype: float64

In [54]:
ser1[:3].combine_first(ser2[:3])

1    0.159451
2    0.699850
3    0.754945
4    0.741397
5    0.446231
dtype: float64

**Pivoting** --  to 
rearrange the data by column values on rows or vice versa.


> Pivoting with Hierarchical Indexing

>> • Stacking—Rotates or pivots the data structure converting columns 
to rows

>> • Unstacking—Converts rows into columns



In [55]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [56]:
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [57]:
ser5.unstack()


ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [58]:
ser5.unstack(0)

white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

**Pivoting from “Long” to “Wide” Format**

In [59]:
longframe = pd.DataFrame({ 'color':['white','white','white',
 'red','red','red',
'black','black','black'],
 'item':['ball','pen','mug',
 'ball','pen','mug',
 'ball','pen','mug'],
 'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.348315
1  white   pen  0.580450
2  white   mug  0.163352
3    red  ball  0.912998
4    red   pen  0.156930
5    red   mug  0.223591
6  black  ball  0.999489
7  black   pen  0.412192
8  black   mug  0.689854

In [60]:
wideframe = longframe.pivot('color','item')
wideframe

value                    
item       ball       mug       pen
color                              
black  0.999489  0.689854  0.412192
red    0.912998  0.223591  0.156930
white  0.348315  0.163352  0.580450

# **Removing**
The last stage of data preparation is the removal of columns and rows

In [71]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [72]:
# To remove column data del pop functions are used
del frame1['ball']
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [73]:
frame1.pop('pen')#delete the series and also return the series as a result.



white    1
black    4
red      7
Name: pen, dtype: int32

In [74]:
frame1

pencil
white       2
black       5
red         8

In [75]:
#To remove row index
frame1.drop('white')


pencil
black       5
red         8

# **Data Transformation**
**Removing Duplicates**
> Duplicate rows might be present in a dataframe for various reasons. 

>In dataframes of 
enormous size, the detection of these rows can be very problematic. 

>In this case, pandas 
provides a series of tools to analyze the duplicate data present in large data structures.

>**duplicated()** function applied to a dataframe can detect the rows that appear to 
be duplicated. It returns a series of Booleans where each element corresponds to a row, 
with True if the row is duplicated (i.e., only the other occurrences, not the first), and with 
False if there are no duplicates in the previous elements.

In [37]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
'value': [2,1,3,3,2]})
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [38]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [39]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [40]:
# To delete duplicate rows from the dataframe
dframe=dframe.drop_duplicates()
dframe

color  value
0  white      2
1  white      1
2    red      3

In [41]:
# to know which are the duplicate rows
dframe[dframe.duplicated()]

Empty DataFrame
Columns: [color, value]
Index: []

**Mapping**

Mapping is nothing more than the 
**creation of a list of matches** between two different values, with the ability to bind a value 
to a particular label or string **bold text**.

To **define mapping** there is no better object than** dict objects.**

In [25]:
map = {
 'label1' : 'value1',
 'label2' : 'value2',
}
map

{'label1': 'value1', 'label2': 'value2'}

**Replacing Values via Mapping**
> Sometimes in a dataset, the text may be in a foreign language, or may be a synonym 
of another value, or may not be expressed in the desired shape. 
 In such cases, a replace 
operation **bold text** of various values is often a necessary process.

• replace()—Replaces values
• map()—Creates a new column
• rename()—Replaces the index value

In [76]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','rosso','verde','rosso','yellow'],
 'price':[5.56,4.20,1.30,0.56,2.75]})
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   rosso   0.56
4  ashtray  yellow   2.75

In [77]:
newcolors = {
'rosso': 'red',
 'verde': 'green',
 '$$$$': 'violet'
 }

In [78]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil     red   0.56
4  ashtray  yellow   2.75

In [66]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [67]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

**Adding Values via Mapping**
> to substitute values by mapping correspondences. 

In [68]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [32]:
prices = {
'ball' : 5.56,
 'mug' : 4.20,
 'bottle' : 1.30,
 'scissors' : 3.41,
 'pen' : 1.30,
 'pencil' : 0.56,
 'ashtray' : 2.75
 }

In [79]:
frame['price'] = frame['item'].map(prices)
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   rosso   0.56
4  ashtray  yellow   2.75

**Rename the Indexes of the Axes**
>  to **replace the label indexes**, pandas provides the **rename() **function, which 
takes the mapping as an argument, that is, a dict object.

In [70]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [71]:
reindex = {
0: 'first',
 1: 'second',
 2: 'third',
3: 'fourth',
 4: 'fifth'}

In [72]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [73]:
 recolumn = {
'item':'object',
'price': 'value'}
frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [74]:
frame.rename(index={1:'first'}, columns={'item':'object'})
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [75]:
frame.rename(columns={'item':'object'}, inplace=True)
frame

object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

**Discretization and Binning**

**> CASE 1**
>>to 
handle large quantities of data generated in sequence.

>> To carry out an analysis of the 
data, however, it is necessary to transform this data into discrete categories, for example, 
by dividing the range of values of such readings into smaller intervals and counting the 
occurrence or statistics in them.

**> CASE 2**

>>Another case might be when you have a huge number 
of samples due to precise readings on a population. 

>>Even here, to facilitate analysis of 
the data, it is necessary to divide the range of values into categories and then analyze the 
occurrences and statistics related to each.

Method 1: Provide data and the bin information

In [89]:
results = [12,34,67,51,28,90,99,12,3,56,74,44,87,23,49,89,87]
# to define an array containing the values of separation of bin
bins = [0,25,50,75,100]

In [90]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [91]:
cat.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]], dtype='interval[int64, right]')

In [92]:
 cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

In [93]:
pd.value_counts(cat)

(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
dtype: int64

In [94]:
 bin_names = ['unlikely','less likely','likely','highly likely']

In [95]:
pd.cut(results, bins, labels=bin_names)

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

Method 2: metion no. of categories required

In [98]:
r1=pd.cut(results, 5)
r1

[(2.904, 22.2], (22.2, 41.4], (60.6, 79.8], (41.4, 60.6], (22.2, 41.4], ..., (79.8, 99.0], (22.2, 41.4], (41.4, 60.6], (79.8, 99.0], (79.8, 99.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.904, 22.2] < (22.2, 41.4] < (41.4, 60.6] < (60.6, 79.8] < (79.8, 99.0]]

In [99]:
 pd.value_counts(r1)

(79.8, 99.0]     5
(41.4, 60.6]     4
(2.904, 22.2]    3
(22.2, 41.4]     3
(60.6, 79.8]     2
dtype: int64

Mention 3: qcut()

In [101]:
#qcut() will ensure that the number of occurrences for each bin is equal, but the edges of each bin vary.
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] <
                                    (87.0, 99.0]]

In [98]:
 pd.value_counts(quintiles)

(62.6, 87.0]     4
(2.999, 24.0]    4
(87.0, 99.0]     3
(46.0, 62.6]     3
(24.0, 46.0]     3
dtype: int64