In [1]:
import numpy as np 
a = np.arange(start=1, stop=10, step=2)
a

array([1, 3, 5, 7, 9])

In [2]:
a = np.array(range(0,9))
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
x =  np.arange(2, 11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
a = np.array(range(0,10))
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
m = np.array([[1,1,1],[1,0,1],[1,1,1]])
m

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [6]:
a = np.random.randint(7,size=(4,4))
a

array([[1, 4, 0, 6],
       [5, 4, 3, 3],
       [3, 2, 1, 2],
       [0, 0, 6, 2]])

In [7]:
a[0:1]

array([[1, 4, 0, 6]])

In [8]:
a[0:2]

array([[1, 4, 0, 6],
       [5, 4, 3, 3]])

In [9]:
a[2:]

array([[3, 2, 1, 2],
       [0, 0, 6, 2]])

In [10]:
a[0:2]*a[2:]

array([[ 3,  8,  0, 12],
       [ 0,  0, 18,  6]])

In [11]:
a = np.random.randint(7,size=(3,4))
b =list(a.sum(axis=1))
print(a)
print("The highest sum column is {}".format(b.index(max(b))))

[[6 5 3 1]
 [5 5 1 0]
 [0 1 0 5]]
The highest sum column is 0
